### ISSUE TITLE
[Feature Request] Use local components in custom markup

### ISSUE THREAD

**Issue by JacobRex** [privatenumber/md-vue-loader#78]
**Problem**
I'm using md-vue-loader in a nuxt application. I'm trying to add features like a copy button and the ability to switch between Vue.js and the rendered HTML to my code demos. This is difficult to manage within the nuxt config, and I think it would be better handled by a dedicated component.

`this.addComponent` allows for the inclusion of external components, but I'd like to manage the code demo component in the same repo as my documentation website.

**Describe the solution you'd like**
I'd like to be able to import and use local components in the code demos. Perhaps something like this, where DemoBuilder is a component in my nuxt application:

```
buildDemos(LiveDemo, DemoFiles, DemoBuilder) {
    return `
      <demo-builder files="${DemoFiles}">
          ${LiveDemo}
      </demo-builder>
    `;
  }
```

**Describe alternatives you've considered**
I could build an external package to handle this, but this would be cumbersome to manage.

**Comment by privatenumber** [comment]
You should be able to do this via `this.addComponent()`:

```diff
buildDemos(LiveDemo, DemoFiles) {
+    this.addComponent('DemoBuilder', '/absolute/path/to/DemoBuilder.vue');

     return `
       <demo-builder files="${DemoFiles}">
           ${LiveDemo}
       </demo-builder>
     `;
}
```

Use something like `path.resolve()` to get the absolute path.

**Comment by JacobRex** [comment]
I've confirmed that your suggestion works - thanks! Feel free to close this issue. Perhaps it's worth adding a note about this to the readme? For example, it would be useful to know the schema of the demoFiles array.
