### ISSUE TITLE
[Feature Request] Richer Multi-File Demo's

### ISSUE THREAD

**Issue by JacobRex** [privatenumber/md-vue-loader#79]
### Contingency
This is contingent on https://github.com/privatenumber/md-vue-loader/issues/78, since I would need to be able to use my own Vue components to do this.

**Problem**
Suppose you're documenting a button with multiple variants. You could create a demo for each variant, but this makes for an ugly and large page. You could create a single demo that includes each button variant, but then you need to add additional markup that complicates the demo. Additionally, if you want to copy code from a demo, you now must copy the entire complex demo with layout markup rather than just a single button's code.

**Describe the solution you'd like**
I'd like the ability to create a component that can handle the display and functionality of multi file demos in a more powerful way. To do this, I need to be able to recieve the name, live demo, and code of each file.

In my case, I'm imagining a custom component that adds styles to each node passed in to put each demo in its own cell of a grid. I'm also imagining that clicking a cell changes the code sample to the selected cell. In the screenshot below, 3 buttons are being documented, and the first one is selected so a blue border is applied and that code is shown.

![image](https://user-images.githubusercontent.com/11563996/100675135-f9a6ca80-332b-11eb-9e13-c1a215d25d12.png)

**Describe alternatives you've considered**
 I accomplished this in the past by creating complex demo's with additional markup in them. See https://pp-design-system.firebaseapp.com/components/button as an example. I think I could create a component that puts each node passed into it into its own cell.

**Comment by privatenumber** [comment]
If I'm understanding the ask correctly, this is already possible with the API solution I gave [here](https://github.com/privatenumber/md-vue-loader/issues/78#issuecomment-736166103).

**Comment by JacobRex** [comment]
The limiting factor on my end might be Vue 2.0. I think that I would need to pass each button demo to my documentation component with no wrapper, so that the component could see and process each node. I've demo'd what i think this would need to look like below.

Are you imagining another scenario or possible approach?

**Desired Approach**

```vue
<template>
  <primary-button />
  <secondary-button />
  <ghost-button />
</template>

<script>
import PrimaryButton from 'doc/PrimaryButton.vue';
import SecondaryButton from 'doc/SecondaryButton.vue';
import GhostButton from 'doc/GhostButton.vue';

export default {
  components: {
    PrimaryButton,
    SecondaryButton,
    GhostButton,
  },
};
</script>
```

_PrimaryButton.vue_
```vue
<template>
  <pp-button variant="primary">Primary</pp-button>
</template>

<script>
import { PpButton } from 'ppds/components/Button';

export default {
  components: {
    PpButton,
  },
};
</script>
```

_SecondaryButton.vue_
```vue
<template>
  <pp-button>Secondary</pp-button>
</template>

<script>
import { PpButton } from 'ppds/components/Button';

export default {
  components: {
    PpButton,
  },
};
</script>
```

_GhostButton.vue_
```vue
<template>
  <pp-button variant="ghost">Ghost</pp-button>
</template>

<script>
import { PpButton } from 'ppds/components/Button';

export default {
  components: {
    PpButton,
  },
};
</script>
```

**Comment by privatenumber** [comment]
Returning multiple root nodes in Vue 2 is possible with [vue-frag](https://github.com/privatenumber/vue-frag).

Going back to the feature request, is there a specific API change you want to request on mdvue-loader?

**Comment by JacobRex** [comment]
The request was for the name, live demo, and code of each file included in a demo, or perhaps just name and code.  This may already be possible, but I'm having trouble passing the demoFiles to a custom component. Consider this config:

```
const path = require('path');
...
{
  test: /\.md$/,
  use: [
    'vue-loader',
    {
      loader: 'md-vue-loader',
      options: {
        buildDemos(LiveDemo, demoFiles) {
          this.addComponent('DemoBuilder', path.resolve(__dirname, './components/DemoBuilder/DemoBuilder.vue'));
          const listFiles = demoFiles.map(file => ({ name: file.name, content: file.content }));
          
          console.log(listFiles);
          /* If logged here, listFiles returns an array of Objects
          * [
          *   {
          *     name: undefined,
          *     content: '<template>\n' +
          *       '\t<o-button @click="openAlert()">\n' +
          *       ....
          *       '</script>\n'
          *   },
          *   {
          *     name: 'AlertDemoNoEscape.vue',
          *     content: '<template>\n' +
          *      ...
          *       '</script>\n'
          *   }
          * ]
          */

           // In my custom component DemoBuilder, I console.log files on mount and get a string "[object Object]". I need the array of objects I attempted to pass in.
          return `<demo-builder files="${listFiles}" />`;
        }
      },
    }
  ],
},
```

**Comment by privatenumber** [comment]
`buildDemos` returns a static template string, which behaves differently from a Vue template.

You can stringify the array and pass it in:

```js
const listFiles = JSON.stringify(demoFiles);

return `<demo-builder :files='${listFiles}' />`;
```

Since the stringified array can contain single or double quotes, you might have to run it through a sanitizer to escape them (eg. `listFiles.replace(/"/g, '\\"')`)

**Comment by JacobRex** [comment]
Perhaps I was unclear. I want `files` to be an array of all of the files included in the demo, not a string. I believe this is simply what the `demoFiles` Array is, but I'm unable to pass it to my component for some reason. I'd like each item in this array should have a name, demo and code or at least name/code. This would allow me to construct something like the mockup. I don't think a stringified array would help?

```
buildDemos(LiveDemo, demoFiles) {
  this.addComponent('DemoBuilder', path.resolve(__dirname, './components/DemoBuilder/DemoBuilder.vue'));
  return `
    <!-- Doesn't work. See error screenshot -->
    <demo-builder :files="${demoFiles}" />
      ${LiveDemo}
    </demo-builder>
  `;
}
```

![image](https://user-images.githubusercontent.com/11563996/100786342-9a9e8f80-33d7-11eb-806f-9eff55c47a2c.png)


**Why tho?**
I need the code samples and the live demo's in the component so that I can:

- add buttons in the demo to switch between html/vue 
- add a button to copy the code
- allow for the ability to "select" demos and change which file's code is being shown

**Comment by privatenumber** [comment]
`JSON.stringify` is for string interpolation. Once in the template the `:` in `:files` will convert it back to an array.

**Comment by JacobRex** [comment]
For the following code:

```
buildDemos(LiveDemo, demoFiles) {
  this.addComponent('DemoBuilder', path.resolve(__dirname, './components/DemoBuilder/DemoBuilder.vue'));
  let listFiles = JSON.stringify(demoFiles);

  return `
    <demo-builder :files="${listFiles}">
      ${LiveDemo}
    </demo-builder>
  `;
}
```

I get the following errors in...

**Terminal Console:**
`Unknown word` errors:
![image](https://user-images.githubusercontent.com/11563996/100793059-397bb980-33e1-11eb-88aa-57ed957e6013.png)

**Browser Console:**
`no matching end tag`:
![image](https://user-images.githubusercontent.com/11563996/100793188-6334e080-33e1-11eb-92b7-6c0641d057c6.png)

`text "\n\t" outside root element will be ignored.`
![image](https://user-images.githubusercontent.com/11563996/100793412-ac853000-33e1-11eb-9906-a0fcb9e52cfb.png)

I believe we may need to clean up the array before it gets passed in, and to be careful about which quotes we replace.

Btw, I'm consuming and attempting to document components from https://github.com/square/orbit

**Comment by privatenumber** [comment]
Yep, that's why I used single quotes in my code example and encouraged sanitization in my comment [here](https://github.com/privatenumber/md-vue-loader/issues/79#issuecomment-736733077).

As a sanitization strategy, you can also use JSON.stringify twice:
```js

return `
  <demo-builder :files=${JSON.stringify(JSON.stringify(listFiles))}>
    ${LiveDemo}
  </demo-builder>
`;
```

Note, the lack of quotes around the string interpolation is deliberate because the output comes with quotes.

**Comment by privatenumber** [comment]
Closing as this is already possible.

Happy to answer any further questions on how in this closed thread.
