### ISSUE TITLE
[Feature Request] Editable demos

### ISSUE THREAD

**Issue by JacobRex** [privatenumber/md-vue-loader#95]
**Problem**
Engineers viewing documentation often want to modify / test the code that they see. Doing this requires them to spin up an environment with the vue component they want to test which isn't always possible or easy. "Knobs" or "controls" like those found in [storybook](https://storybook.js.org/docs/react/essentials/controls) have been requested to make demos editable but this is complex to implement and only works for simple components.

**Describe the solution you'd like**
I'd like it if the code block was editable and would update the vue demo rendered above. This would allow engineers to understand the components without having to have an environment up and running.

**Describe alternatives you've considered**
* Switching to Storybook
* Creating my own live demo with knobs/controls
* Leveraging tools like codesandbox
* Sticking with static demos

**Comment by privatenumber** [comment]
This is a Webpack loader for compiling Markdown to Vue so what the demos look like and do are out of scope.

There's a [buildDemos](https://github.com/privatenumber/md-vue-loader#wrapping-demos-in-custom-markup) hook you can use to achieve that though. You can pass in a code editor (eg. Monaco Editor) but I'm not sure how you'll handle on-demand SFC compilation. You can also embed a Codesandbox here.

**Comment by JacobRex** [comment]
I'm looking into using tools like https://github.com/vue-styleguidist/vue-live which lets you build editable code demos pretty easily. In order to use something like this, I need to pass in the markup and the [components](https://github.com/vue-styleguidist/vue-live#components) that appear in that markup. Would it be possible for `buildDemos` to provide the components used in the demo? I'm imagining a usage like like:

```
 buildDemos(demoFiles, Components) {
  const code = demoFiles.map(file => ent.encode(file.content));
  this.addComponent('DemoBuilder', '~/components/DemoBuilder/DemoBuilder.vue');
  return `<demo-builder :components="Components">${code}</demo-builder>`;
}
```

Where `Components` is an object with:
- **key**: registration name
- **value**: VueJs component object
